version: '3.1'

# base service definitions, environment variables secrets should be updated and loaded from docker-compose.secrets.yml

services:
  db:
    image: postgres:9.6.8-alpine
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
